name: by_faith_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  material_symbols_icons: ^4.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  provider: ^6.1.2
  flutter_quill: 11.4.1
  mapsforge_flutter: ^3.0.1
  path_provider: ^2.1.5
  http: ^1.2.2
  archive: ^3.5.1
  file_picker: ^10.1.8
  url_launcher: ^6.1.5
  connectivity_plus: ^6.0.5
  onboarding: ^4.0.2
  fastforge: ^0.5.1
  characters: ^1.4.0
  collection: ^1.18.0
  vector_math: ^2.1.4

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/bible_data/akjv.json
    - lib/bible_data/kjv.json
    - lib/bible_data/book.chapters.json
    - lib/bible_data/kjv-strongs-numbers.json
    - lib/bible_data/strongs-greek-dictionary.json
    - lib/bible_data/strongs-hebrew-dictionary.json
    - lib/bible_data/websters1828dictionary.json
    - lib/assets/maps/world.map
    - lib/assets/maps/render_themes/defaultrender.xml
    - lib/assets/maps.json
    - lib/assets/map_coordinates.json